name: Tests

on: [push]

jobs:
  xcode_tests:
    name: Tests
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run Tests
        run: swift run --configuration release --skip-update --package-path ./CIDependencies/ xcutils test iOS --scheme Composed --enable-code-coverage
